// Crear productos deportivos
const products = [
  {id: 1, name: 'Mao-chan', price: 100, img: 'Images/cards/1.jpg', categorie: 'Acción',quantity: 1,},
  {id: 2, name: 'Yukinai Endro', price: 200, img: 'Images/cards/2.jpg', categorie: 'Acción',quantity: 1,},
  {id: 3, name: 'Kakashi', price: 300, img: 'Images/cards/3.jpg', categorie: 'Aventura',quantity: 1,},
  {id: 4, name: 'Hajimeru', price: 400, img: 'Images/cards/4.jpg', categorie: 'Aventura',quantity: 1,},
  {id: 5, name: 'Sailor Marte', price: 500, img: 'Images/cards/5.jpg', categorie: 'Terror',quantity: 1,},
  {id: 6, name: 'Neko', price: 600, img: 'Images/cards/6.jpg', categorie: 'Terror',quantity: 1,},
  {id: 7, name: 'Kurumi', price: 700, img: 'Images/cards/7.jpg', categorie: 'Romance',quantity: 1,},
  {id: 8, name: 'Mitsuri', price: 800, img: 'Images/cards/8.jpg', categorie: 'Romance',quantity: 1,},
  {id: 9, name: 'Tejina', price: 900, img: 'Images/cards/9.jpg', categorie: 'Ficción',quantity: 1,},
  {id: 10, name: 'Rem', price: 1000, img: 'Images/cards/10.jpg', categorie: 'Aventura',quantity: 1,},
  {id: 11, name: 'Zero Two', price: 1100, img: 'Images/cards/11.jpg', categorie: 'Terror',quantity: 1,},
  {id: 12, name: 'Rio Futaba', price: 1200, img: 'Images/cards/12.jpg', categorie: 'Ficción',quantity: 1,},
];


  // {id: 13, name: 'element 13', price: 0, img: '.jpg', categorie: 'unknown'},
  // {id: 14, name: 'element 14', price: 0, img: '.jpg', categorie: 'unknownn'},
  // {id: 15, name: 'element 15', price: 0, img: '.jpg', categorie: 'unknown'},
  // {id: 16, name: 'element 16', price: 0, img: '.jpg', categorie: 'unknown'},
  // {id: 17, name: 'element 17', price: 0, img: '.jpg', categorie: 'unknown'},
  // {id: 18, name: 'element 18', price: 0, img: '.jpg', categorie: 'unknown'},
  // {id: 19, name: 'element 19', price: 0, img: '.jpg', categorie: 'unknown'},
  // {id: 20, name: 'element 20', price: 0, img: '.jpg', categorie: 'unknown'},
  // {id: 21, name: 'element 21', price: 0,img: '.jpg', categorie: 'unknown'},
  // {id: 22, name: 'element 22', price: 0,img: '.jpg', categorie: 'unknown'},
  // {id: 23, name: 'element 23', price: 0,img: '.jpg', categorie: 'unknown'},
  // {id: 24, name: 'element 24', price: 0,img: '.jpg', categorie: 'unknown'},
  // {id: 25, name: 'element 25', price: 0,img: '.jpg', categorie: 'unknown'},
  // {id: 26, name: 'element 26', price: 0,img: '.jpg', categorie: 'unknown'},
  // {id: 27, name: 'element 27', price: 0,img: '.jpg', categorie: 'unknown'},
  // {id: 28, name: 'element 28', price: 0,img: '.jpg', categorie: 'unknown'},
  // {id: 29, name: 'element 29', price: 0,img: '.jpg', categorie: 'unknown'},
  // {id: 30, name: 'element 30', price: 0,img: 'I.jpg', categorie: 'unknown'},
